### ISSUE TITLE
Character limit for lines

### ISSUE THREAD

**Issue by Flamefire** [ComputationalRadiationPhysics/contributing#4] opened 2015-11-25 11:35 UTC
I'd vote against the 80 char limit as this is pretty narrow especially on current wide screen monitors. For 4:3 it was reasonable but now? I'd choose 100-120 as a limit. Almost 240 chars fit on a screens width, so 110 would be a good choice (a bit below half of the screen)
Choosing a low limit means lots of lines and much vertical scrolling to avoid the (much less often) required horizontal scrolling.
I can't follow the reason that (some) terminals are by default 80 chars wide. You can configure that...
So only point where horizontal scrolling MIGHT be required then is a 3 way merge and only when the conflicting line is really that long.

**Comment by ax3l** [comment] 2015-11-25 14:07
[Besides the listed ones](https://github.com/ComputationalRadiationPhysics/contributing/issues/2#issuecomment-159303617) the main reason is really that a **3-way merge** must fit and with, e.g., 100 chars that's already 300 which is too much for most (portable) screens.

Also vertical scrolling on github is a mess during reviews, but they do still work with ~100 chars.

**Comment by Flamefire** [comment] 2015-11-25 14:34
Ok then let me address the reasons one by one:

1. Terminals open by default as 80 columns:   
Emphasize ***by default*** I don't see an arbitrary default setting a reason for setting the maximum width. And really: Why use terminals anyway except for quick checks? There are enough reasonable editors and IDEs out there...
2. a 3 way merge must fit a screen:   
Really a ***must***? How often will real 3-way merges be done? 0.1% of the time with 90% developing and 9.9% regular commits/merges? And there will be only a small amount of lines with >80 chars so chances are high, that the conflicting ones can be resolved without vertical scrolling. Wrapping those at 80 means however more horizontal scrolling in all other cases.
3. avoid vertical scrolling during reviews on GitHub:   
This will also be avoided on even 120 chars. Just checked that.

To quote you: 

>everyone would love 100 or 120 chars ;)

So why don't use that just for due to a slight discomfort on a rarely occurring case?

**Comment by ax3l** [comment] 2015-11-25 14:38
I feel your pain but please try to feel the pain of someone developing a feature that horribly collides with someone else and then trying to resolve the conflict. The problem is, even if we try to avoid conflicting code by communicating it is a bug must to make the process of resolving those as easy as possible because peoples work depend on it.

**Comment by ax3l** [comment] 2018-11-20 08:51
Update 2018: currently, 100 chars seem to fit well on GitHub code reviews side-by-side and higher resolutions and wide-screen laptops are more common.

Nevertheless, as an example for 3-way-diffs, 3x100 chars do still not fit even an external monitor (1920x1080px), e.g. in `kdiff3`.
Personally I could still live with that as long as the two-way diff works (also fits with 100 chars on e.g. a 1600x900px laptop screen).

**Comment by theZiz** [comment] 2018-11-20 08:57
I made the experience that 80 characters per line can be read very well and work also very well in not-full-screen developing environments. There is a a reason why papers, journals etc. are two- or more column. It is way more easy for humas to get a narrow text than a wide.

I personally would stay with 80 characters. Imho it also works very well with our newline-centric coding guide lines. :wink:

**Comment by ax3l** [comment] 2018-11-20 08:59
I mean there are also ergonomic & typographic reasons not to take more: [SO](https://softwareengineering.stackexchange.com/a/222998)

**Comment by bernhardmgruber** [comment] 2020-11-17 12:01
This issue is resolved after the discussion and vote in: https://github.com/ComputationalRadiationPhysics/contributing/pull/39

**Closed** 2021-04-08 04:36 UTC
Labels: C++ Style, Python Style
